FROM --platform=linux/${TARGETARCH} apache/airflow:3.0.1-python3.9

USER root

RUN apt-get update \
    && apt-get install -y iputils-ping \
    && apt-get install -y --no-install-recommends \
         openjdk-17-jre-headless \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
RUN export JAVA_HOME

RUN pip install --no-cache-dir apache-airflow-providers-apache-spark==4.9.0 \
                               pyspark==3.3.2 \
                               airflow-provider-great-expectations==0.3.0 \
                               astronomer-cosmos==1.10.0 \
                               dbt-core==1.9.4 \
                               dbt-bigquery==1.9.1

COPY ./conf/spark-defaults.conf /home/airflow/.local/lib/python3.9/site-packages/pyspark/conf/spark-defaults.conf
COPY ./conf/metrics.properties /home/airflow/.local/lib/python3.9/site-packages/pyspark/conf/metrics.properties
COPY ./jars/gcs-connector-hadoop3-latest.jar /home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/gcs-connector-hadoop3-latest.jar
ENV SPARK_CONF_DIR=/home/airflow/.local/lib/python3.9/site-packages/pyspark/conf
