FROM apache/airflow:2.6.0

RUN pip install --no-cache-dir astronomer-cosmos==0.6.5 \
                               dbt-core==1.5.0 \
                               dbt-bigquery==1.5.0 \
                               great_expectations==0.16.11
