greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_pyth_bigquery:
      type: bigquery
      method: service-account
      project: white-sign-386415
      dataset: dbt_pyth
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/white-sign-386415-c2017e5e912f.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: white-sign-386415
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/white-sign-386415-c2017e5e912f.json
      location: asia-southeast1

  target: dbt_pyth_bigquery