greenery:

  outputs:
    dbt_mui:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_mui

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_mui_bigquery:
      type: bigquery
      method: service-account
      project: deb-1-by-skooldio
      dataset: dbt_mui
      threads: 1
      keyfile: /Users/bsaejia/data-engineering-bootcamp/00-bootcamp-project/dags/deb-1-by-skooldio-9c5dab1f27c8.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: deb-1-by-skooldio
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/dags/deb-1-by-skooldio-9c5dab1f27c8.json
      location: asia-southeast1

  target: dbt_mui_bigquery