FROM apache/airflow:2.7.0

RUN pip install --no-cache-dir great_expectations==0.16.11 \
                               astronomer-cosmos==0.6.5 \
                               dbt-core==1.5.0 \
                               dbt-bigquery==1.5.0