FROM apache/airflow:2.8.1

RUN pip install --no-cache-dir airflow-provider-great-expectations==0.2.7 \
                               astronomer-cosmos==1.3.2 \
                               dbt-core==1.7.9 \
                               dbt-bigquery==1.7.6
